START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE TABLE tenants_admin_permissions (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(100) NOT NULL,
        name character varying(150) NOT NULL,
        CONSTRAINT "PK_tenants_admin_permissions" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE TABLE tenants_admin_roles (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        code character varying(50) NOT NULL,
        name character varying(100) NOT NULL,
        CONSTRAINT "PK_tenants_admin_roles" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE TABLE tenants_admin (
        id uuid NOT NULL DEFAULT (uuidv7()),
        username character varying(100) NOT NULL,
        password_hash text NOT NULL,
        is_active boolean NOT NULL DEFAULT TRUE,
        role_id integer NOT NULL,
        created_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        updated_at timestamp with time zone NOT NULL DEFAULT (NOW()),
        is_deleted boolean NOT NULL DEFAULT FALSE,
        deleted_at timestamp with time zone,
        CONSTRAINT "PK_tenants_admin" PRIMARY KEY (id),
        CONSTRAINT "FK_tenants_admin_tenants_admin_roles_role_id" FOREIGN KEY (role_id) REFERENCES tenants_admin_roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE TABLE tenants_admin_role_permissions (
        role_id integer NOT NULL,
        permission_id integer NOT NULL,
        CONSTRAINT "PK_tenants_admin_role_permissions" PRIMARY KEY (role_id, permission_id),
        CONSTRAINT "FK_tenants_admin_role_permissions_tenants_admin_permissions_pe~" FOREIGN KEY (permission_id) REFERENCES tenants_admin_permissions (id) ON DELETE CASCADE,
        CONSTRAINT "FK_tenants_admin_role_permissions_tenants_admin_roles_role_id" FOREIGN KEY (role_id) REFERENCES tenants_admin_roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE INDEX idx_tenants_admin_active_created_at_id ON tenants_admin (created_at, id) WHERE "is_deleted" = false;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE INDEX "IX_tenants_admin_role_id" ON tenants_admin (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE UNIQUE INDEX "IX_tenants_admin_username" ON tenants_admin (username);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE UNIQUE INDEX "IX_tenants_admin_permissions_code" ON tenants_admin_permissions (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE INDEX "IX_tenants_admin_role_permissions_permission_id" ON tenants_admin_role_permissions (permission_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    CREATE UNIQUE INDEX "IX_tenants_admin_roles_code" ON tenants_admin_roles (code);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260213114227_AddTenantsAdmin') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260213114227_AddTenantsAdmin', '10.0.2');
    END IF;
END $EF$;
COMMIT;

